SET NOCOUNT ON;
INSERT INTO IanaTimeZones (IanaIdentifier, DisplayName) VALUES
(N'Africa/Abidjan', N'Greenwich Mean Time (Abidjan)'),
(N'Africa/Cairo', N'Eastern European Time (Cairo)'),
(N'Africa/Johannesburg', N'South Africa Standard Time'),
(N'America/Anchorage', N'Alaska Time'),
(N'America/Argentina/Buenos_Aires', N'Argentina Time (Buenos Aires)'),
(N'America/Bogota', N'Colombia Time'),
(N'America/Caracas', N'Venezuela Time'),
(N'America/Chicago', N'Central Time (US & Canada)'),
(N'America/Denver', N'Mountain Time (US & Canada)'),
(N'America/Halifax', N'Atlantic Time (Canada)'),
(N'America/Los_Angeles', N'Pacific Time (US & Canada)'),
(N'America/Mexico_City', N'Central Time (Mexico)'),
(N'America/New_York', N'Eastern Time (US & Canada)'),
(N'America/Phoenix', N'Mountain Time (no DST)'),
(N'America/Santiago', N'Chile Time'),
(N'America/Sao_Paulo', N'Brasilia Time'),
(N'America/St_Johns', N'Newfoundland Time'),
(N'America/Toronto', N'Eastern Time (Canada)'),
(N'America/Vancouver', N'Pacific Time (Canada)'),
(N'Asia/Bangkok', N'Indochina Time'),
(N'Asia/Dubai', N'Gulf Standard Time'),
(N'Asia/Hong_Kong', N'Hong Kong Time'),
(N'Asia/Jakarta', N'Western Indonesia Time'),
(N'Asia/Jerusalem', N'Israel Time'),
(N'Asia/Kolkata', N'India Standard Time'),
(N'Asia/Manila', N'Philippine Time'),
(N'Asia/Seoul', N'Korea Standard Time'),
(N'Asia/Shanghai', N'China Standard Time'),
(N'Asia/Singapore', N'Singapore Time'),
(N'Asia/Taipei', N'Taipei Time'),
(N'Asia/Tokyo', N'Japan Standard Time'),
(N'Australia/Adelaide', N'Australian Central Time'),
(N'Australia/Brisbane', N'Australian Eastern Time (Queensland)'),
(N'Australia/Melbourne', N'Australian Eastern Time'),
(N'Australia/Perth', N'Australian Western Time'),
(N'Australia/Sydney', N'Australian Eastern Time (New South Wales)'),
(N'Europe/Amsterdam', N'Central European Time (Netherlands)'),
(N'Europe/Berlin', N'Central European Time (Germany)'),
(N'Europe/Brussels', N'Central European Time (Belgium)'),
(N'Europe/Dublin', N'Greenwich Mean Time (Ireland)'),
(N'Europe/Helsinki', N'Eastern European Time (Finland)'),
(N'Europe/Istanbul', N'Turkey Time'),
(N'Europe/Lisbon', N'Western European Time (Portugal)'),
(N'Europe/London', N'Greenwich Mean Time / UK Time'),
(N'Europe/Madrid', N'Central European Time (Spain)'),
(N'Europe/Moscow', N'Moscow Time'),
(N'Europe/Paris', N'Central European Time (France)'),
(N'Europe/Prague', N'Central European Time (Czechia)'),
(N'Europe/Rome', N'Central European Time (Italy)'),
(N'Europe/Stockholm', N'Central European Time (Sweden)'),
(N'Europe/Vienna', N'Central European Time (Austria)'),
(N'Europe/Warsaw', N'Central European Time (Poland)'),
(N'Europe/Zurich', N'Central European Time (Switzerland)'),
(N'Pacific/Auckland', N'New Zealand Time'),
(N'Pacific/Fiji', N'Fiji Time'),
(N'Pacific/Honolulu', N'Hawaii-Aleutian Time'),
(N'UTC', N'Coordinated Universal Time (UTC)');
