// <auto-generated />
using System;
using AchievementTracker.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AchievementTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402023953_FixAppUserLocationConstraintIfMissing")]
    partial class FixAppUserLocationConstraintIfMissing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Handle")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("IanaTimeZoneId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsListedOnLeaderboards")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocationCityId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationCountryId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationStateRegionId")
                        .HasColumnType("int");

                    b.Property<int?>("PronounOptionId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AppUserId");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasFilter("[Handle] IS NOT NULL");

                    b.HasIndex("IanaTimeZoneId");

                    b.HasIndex("LocationCityId");

                    b.HasIndex("LocationCountryId");

                    b.HasIndex("LocationStateRegionId");

                    b.HasIndex("PronounOptionId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUserPinnedAchievement", b =>
                {
                    b.Property<int>("AppUserPinnedAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserPinnedAchievementId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("PlatformId")
                        .HasColumnType("tinyint");

                    b.Property<int>("SteamAchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AppUserPinnedAchievementId");

                    b.HasIndex("SteamAchievementId");

                    b.HasIndex("AppUserId", "PlatformId", "SteamAchievementId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("AppUserPinnedAchievements", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUserSocialLink", b =>
                {
                    b.Property<int>("AppUserSocialLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserSocialLinkId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("LinkValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte>("Platform")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AppUserSocialLinkId");

                    b.HasIndex("AppUserId", "Platform")
                        .IsUnique();

                    b.ToTable("AppUserSocialLinks", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.IanaTimeZone", b =>
                {
                    b.Property<int>("IanaTimeZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IanaTimeZoneId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IanaIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IanaTimeZoneId");

                    b.HasIndex("IanaIdentifier")
                        .IsUnique();

                    b.ToTable("IanaTimeZones", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.LocationCity", b =>
                {
                    b.Property<int>("LocationCityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationCityId"));

                    b.Property<int>("LocationStateRegionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("LocationCityId");

                    b.HasIndex("LocationStateRegionId", "Name")
                        .IsUnique();

                    b.ToTable("LocationCities", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.LocationCountry", b =>
                {
                    b.Property<int>("LocationCountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationCountryId"));

                    b.Property<string>("IsoAlpha2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("LocationCountryId");

                    b.HasIndex("IsoAlpha2")
                        .IsUnique();

                    b.ToTable("LocationCountries", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.LocationStateRegion", b =>
                {
                    b.Property<int>("LocationStateRegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationStateRegionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("LocationCountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("LocationStateRegionId");

                    b.HasIndex("LocationCountryId", "Code")
                        .IsUnique();

                    b.ToTable("LocationStateRegions", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.PronounOption", b =>
                {
                    b.Property<int>("PronounOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PronounOptionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("PronounOptionId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PronounOptions", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.Role", b =>
                {
                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPost", b =>
                {
                    b.Property<int>("SocialPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialPostId"));

                    b.Property<int>("AuthorAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SocialPostId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("CreateDate", "SocialPostId");

                    b.HasIndex("AuthorAppUserId", "CreateDate", "SocialPostId");

                    b.ToTable("SocialPosts", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostAttachment", b =>
                {
                    b.Property<int>("SocialPostAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialPostAttachmentId"));

                    b.Property<short>("AttachmentType")
                        .HasColumnType("smallint");

                    b.Property<string>("Caption")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)100);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SocialPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("SocialPostAttachmentId");

                    b.HasIndex("SocialPostId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("SocialPostAttachments", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostComment", b =>
                {
                    b.Property<int>("SocialPostCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialPostCommentId"));

                    b.Property<int>("AuthorAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("SocialPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SocialPostCommentId");

                    b.HasIndex("AuthorAppUserId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SocialPostId", "CreateDate", "SocialPostCommentId");

                    b.ToTable("SocialPostComments", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostReaction", b =>
                {
                    b.Property<int>("SocialPostId")
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<short>("ReactionType")
                        .HasColumnType("smallint");

                    b.HasKey("SocialPostId", "AppUserId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("SocialPostId");

                    b.ToTable("SocialPostReactions", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DescriptionSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBuggy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsConditionallyObtainable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDLC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDateSpecific")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGrind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsMissable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsMultiplayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRandom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUnobtainable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsViral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWorldRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SteamApiName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("IsHidden");

                    b.HasIndex("GameId", "SteamApiName")
                        .IsUnique();

                    b.ToTable("SteamAchievements", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamAchievementStat", b =>
                {
                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<decimal>("GlobalPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AchievementId");

                    b.ToTable("SteamAchievementStats", null, t =>
                        {
                            t.HasCheckConstraint("CK_SteamAchievementStats_Percentage", "[GlobalPercentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SteamCategories", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamDeveloper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SteamDevelopers", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("HeaderImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRemoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUnlisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SteamAppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SteamAppId")
                        .IsUnique();

                    b.ToTable("SteamGames", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameCategory", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SteamGameCategories", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameDeveloper", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "DeveloperId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("SteamGameDevelopers", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("SteamGameGenres", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameLanguage", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<bool>("HasFullAudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasInterface")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasSubtitles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("GameId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("SteamGameLanguages", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGamePlatform", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<byte>("Platform")
                        .HasColumnType("tinyint");

                    b.HasKey("GameId", "Platform");

                    b.ToTable("SteamGamePlatforms", null, t =>
                        {
                            t.HasCheckConstraint("CK_SteamGamePlatforms_Platform", "[Platform] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGamePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "RecordedAt")
                        .IsDescending(false, true);

                    b.ToTable("SteamGamePrices", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGamePublisher", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PublisherId");

                    b.HasIndex("PublisherId");

                    b.ToTable("SteamGamePublishers", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("MetacriticScore")
                        .HasColumnType("int");

                    b.Property<int?>("Recommendations")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("SteamRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("SteamGameReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_SteamGameReviews_Metacritic", "[MetacriticScore] IS NULL OR ([MetacriticScore] BETWEEN 0 AND 100)");
                        });
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameTag", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("SteamGameTags", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SteamGenres", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SteamLanguages", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamPublisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SteamPublishers", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SteamTags", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamUserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("SteamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("SteamId", "AchievementId")
                        .IsUnique();

                    b.HasIndex("SteamId", "UnlockedAt")
                        .IsDescending(false, true);

                    b.ToTable("SteamUserAchievements", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamUserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlaytimeForever")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("SteamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("SteamId");

                    b.HasIndex("SteamId", "GameId")
                        .IsUnique();

                    b.ToTable("SteamUserGames", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserExternalLogin", b =>
                {
                    b.Property<int>("UserExternalLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserExternalLoginId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<short>("AuthProvider")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserExternalLoginId");

                    b.HasIndex("AppUserId", "AuthProvider")
                        .IsUnique();

                    b.HasIndex("AuthProvider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("UserExternalLogins", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserExternalLogins_AuthProvider", "[AuthProvider] IN (1)");
                        });
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.HasKey("AppUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserSteamProfile", b =>
                {
                    b.Property<long>("SteamId")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarFullUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AvatarMediumUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AvatarSmallUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCheckedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonaName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UserExternalLoginId")
                        .HasColumnType("int");

                    b.HasKey("SteamId");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserExternalLoginId")
                        .IsUnique()
                        .HasFilter("[UserExternalLoginId] IS NOT NULL");

                    b.ToTable("UserSteamProfiles", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUser", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.IanaTimeZone", "IanaTimeZone")
                        .WithMany()
                        .HasForeignKey("IanaTimeZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AchievementTracker.Data.Entities.LocationCity", "LocationCity")
                        .WithMany()
                        .HasForeignKey("LocationCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AchievementTracker.Data.Entities.LocationCountry", "LocationCountry")
                        .WithMany()
                        .HasForeignKey("LocationCountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AchievementTracker.Data.Entities.LocationStateRegion", "LocationStateRegion")
                        .WithMany()
                        .HasForeignKey("LocationStateRegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AchievementTracker.Data.Entities.PronounOption", "PronounOption")
                        .WithMany()
                        .HasForeignKey("PronounOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IanaTimeZone");

                    b.Navigation("LocationCity");

                    b.Navigation("LocationCountry");

                    b.Navigation("LocationStateRegion");

                    b.Navigation("PronounOption");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUserPinnedAchievement", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("PinnedAchievements")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamAchievement", "SteamAchievement")
                        .WithMany()
                        .HasForeignKey("SteamAchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("SteamAchievement");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUserSocialLink", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("SocialLinks")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.LocationCity", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.LocationStateRegion", "StateRegion")
                        .WithMany("Cities")
                        .HasForeignKey("LocationStateRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StateRegion");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.LocationStateRegion", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.LocationCountry", "Country")
                        .WithMany("StateRegions")
                        .HasForeignKey("LocationCountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPost", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("SocialPosts")
                        .HasForeignKey("AuthorAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostAttachment", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SocialPost", "Post")
                        .WithMany("Attachments")
                        .HasForeignKey("SocialPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostComment", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AuthorAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SocialPostComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AchievementTracker.Data.Entities.SocialPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("SocialPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostReaction", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SocialPost", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("SocialPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamAchievement", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("Achievements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamAchievementStat", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamAchievement", "Achievement")
                        .WithOne("Stats")
                        .HasForeignKey("AchievementTracker.Data.Entities.SteamAchievementStat", "AchievementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameCategory", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamCategory", "Category")
                        .WithMany("GameCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GameCategories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameDeveloper", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamDeveloper", "Developer")
                        .WithMany("GameDevelopers")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GameDevelopers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameGenre", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamGenre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameLanguage", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GameLanguages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamLanguage", "Language")
                        .WithMany("GameLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGamePlatform", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("Platforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGamePrice", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("Prices")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGamePublisher", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GamePublishers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamPublisher", "Publisher")
                        .WithMany("GamePublishers")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameReview", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameTag", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GameTags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamTag", "Tag")
                        .WithMany("GameTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamUserAchievement", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamAchievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.UserSteamProfile", "UserSteamProfile")
                        .WithMany()
                        .HasForeignKey("SteamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("UserSteamProfile");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamUserGame", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("UserGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.UserSteamProfile", "UserSteamProfile")
                        .WithMany("UserGames")
                        .HasForeignKey("SteamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("UserSteamProfile");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserRole", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserSteamProfile", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.UserExternalLogin", "ExternalLogin")
                        .WithOne("SteamProfile")
                        .HasForeignKey("AchievementTracker.Data.Entities.UserSteamProfile", "UserExternalLoginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExternalLogin");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUser", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("PinnedAchievements");

                    b.Navigation("SocialLinks");

                    b.Navigation("SocialPosts");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.LocationCountry", b =>
                {
                    b.Navigation("StateRegions");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.LocationStateRegion", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPost", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamAchievement", b =>
                {
                    b.Navigation("Stats");

                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamCategory", b =>
                {
                    b.Navigation("GameCategories");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamDeveloper", b =>
                {
                    b.Navigation("GameDevelopers");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGame", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("GameCategories");

                    b.Navigation("GameDevelopers");

                    b.Navigation("GameGenres");

                    b.Navigation("GameLanguages");

                    b.Navigation("GamePublishers");

                    b.Navigation("GameTags");

                    b.Navigation("Platforms");

                    b.Navigation("Prices");

                    b.Navigation("Reviews");

                    b.Navigation("UserGames");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGenre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamLanguage", b =>
                {
                    b.Navigation("GameLanguages");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamPublisher", b =>
                {
                    b.Navigation("GamePublishers");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamTag", b =>
                {
                    b.Navigation("GameTags");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserExternalLogin", b =>
                {
                    b.Navigation("SteamProfile");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserSteamProfile", b =>
                {
                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
