// <auto-generated />
using System;
using AchievementTracker.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AchievementTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsListedOnLeaderboards")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AppUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });
                
            modelBuilder.Entity("AchievementTracker.Data.Entities.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<string>("ConversationImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConversationTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short>("ConversationType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastMessageDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ConversationId");

                    b.HasIndex("CreatedByAppUserId", "LastMessageDate");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<Guid>("AppUserPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("ConversationParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsMuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("LastReadMessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LeftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversationId", "AppUserPublicId");

                    b.HasIndex("ConversationId", "AppUserId")
                        .IsUnique();

                    b.HasIndex("LastReadMessageId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.DirectMessage", b =>
                {
                    b.Property<long>("DirectMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DirectMessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SenderAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DirectMessageId");

                    b.HasIndex("ConversationId", "SentDate");

                    b.HasIndex("SenderAppUserId");

                    b.ToTable("DirectMessages");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.MessageEmbed", b =>
                {
                    b.Property<long>("MessageEmbedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageEmbedId"));

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("DirectMessageId")
                        .HasColumnType("bigint");

                    b.Property<short>("EmbedType")
                        .HasColumnType("smallint");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("MessageEmbedId");

                    b.HasIndex("DirectMessageId");

                    b.ToTable("MessageEmbeds");
                });
                
            modelBuilder.Entity("AchievementTracker.Data.Entities.Role", b =>
                {
                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserExternalLogin", b =>
                {
                    b.Property<int>("UserExternalLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserExternalLoginId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<short>("AuthProvider")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserExternalLoginId");

                    b.HasIndex("AppUserId", "AuthProvider")
                        .IsUnique();

                    b.HasIndex("AuthProvider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("UserExternalLogins", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserExternalLogins_AuthProvider", "[AuthProvider] IN (1)");
                        });
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.HasKey("AppUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserSteamProfile", b =>
                {
                    b.Property<long>("SteamId")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarFullUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AvatarMediumUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AvatarSmallUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCheckedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonaName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UserExternalLoginId")
                        .HasColumnType("int");

                    b.HasKey("SteamId");

                    b.HasIndex("UserExternalLoginId")
                        .IsUnique()
                        .HasFilter("[UserExternalLoginId] IS NOT NULL");

                    b.ToTable("SteamProfiles", (string)null);
                });

             modelBuilder.Entity("AchievementTracker.Data.Entities.Conversation", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("AppUserPublicId")
                        .HasPrincipalKey("PublicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.DirectMessage", "LastReadMessage")
                        .WithMany()
                        .HasForeignKey("LastReadMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppUser");

                    b.Navigation("Conversation");

                    b.Navigation("LastReadMessage");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.DirectMessage", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderAppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.MessageEmbed", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.DirectMessage", "DirectMessage")
                        .WithMany("Embeds")
                        .HasForeignKey("DirectMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectMessage");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserRole", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserSteamProfile", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.UserExternalLogin", "ExternalLogin")
                        .WithOne("SteamProfile")
                        .HasForeignKey("AchievementTracker.Data.Entities.UserSteamProfile", "UserExternalLoginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExternalLogin");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUser", b =>
                {
                    b.Navigation("ConversationParticipants");
                    
                    b.Navigation("ExternalLogins");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.DirectMessage", b =>
                {
                    b.Navigation("Embeds");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserExternalLogin", b =>
                {
                    b.Navigation("SteamProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
