// <auto-generated />
using System;
using AchievementTracker.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AchievementTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Handle")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsListedOnLeaderboards")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AppUserId");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasFilter("[Handle] IS NOT NULL");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.Role", b =>
                {
                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPost", b =>
                {
                    b.Property<int>("SocialPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialPostId"));

                    b.Property<int>("AuthorAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SocialPostId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("CreateDate", "SocialPostId");

                    b.HasIndex("AuthorAppUserId", "CreateDate", "SocialPostId");

                    b.ToTable("SocialPost", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostAttachment", b =>
                {
                    b.Property<int>("SocialPostAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialPostAttachmentId"));

                    b.Property<short>("AttachmentType")
                        .HasColumnType("smallint");

                    b.Property<string>("Caption")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SocialPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("SocialPostAttachmentId");

                    b.HasIndex("SocialPostId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("SocialPostAttachment", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostComment", b =>
                {
                    b.Property<int>("SocialPostCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialPostCommentId"));

                    b.Property<int>("AuthorAppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("SocialPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SocialPostCommentId");

                    b.HasIndex("AuthorAppUserId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SocialPostId", "CreateDate", "SocialPostCommentId");

                    b.ToTable("SocialPostComment", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostReaction", b =>
                {
                    b.Property<int>("SocialPostId")
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<short>("ReactionType")
                        .HasColumnType("smallint");

                    b.HasKey("SocialPostId", "AppUserId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("SocialPostId");

                    b.ToTable("SocialPostReaction", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserExternalLogin", b =>
                {
                    b.Property<int>("UserExternalLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserExternalLoginId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<short>("AuthProvider")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserExternalLoginId");

                    b.HasIndex("AppUserId", "AuthProvider")
                        .IsUnique();

                    b.HasIndex("AuthProvider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("UserExternalLogins", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserExternalLogins_AuthProvider", "[AuthProvider] IN (1)");
                        });
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.HasKey("AppUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserSteamProfile", b =>
                {
                    b.Property<long>("SteamId")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarFullUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AvatarMediumUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AvatarSmallUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCheckedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonaName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("UserExternalLoginId")
                        .HasColumnType("int");

                    b.HasKey("SteamId");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserExternalLoginId")
                        .IsUnique()
                        .HasFilter("[UserExternalLoginId] IS NOT NULL");

                    b.ToTable("UserSteamProfiles", (string)null);
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamAchievement", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("Achievements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamAchievementStat", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamAchievement", "Achievement")
                        .WithOne("Stats")
                        .HasForeignKey("AchievementTracker.Data.Entities.SteamAchievementStat", "AchievementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameCategory", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamCategory", "Category")
                        .WithMany("GameCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GameCategories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameDeveloper", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamDeveloper", "Developer")
                        .WithMany("GameDevelopers")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GameDevelopers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameGenre", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamGenre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameLanguage", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GameLanguages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamLanguage", "Language")
                        .WithMany("GameLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGamePlatform", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("Platforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGamePrice", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("Prices")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGamePublisher", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GamePublishers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamPublisher", "Publisher")
                        .WithMany("GamePublishers")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameReview", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGameTag", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("GameTags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SteamTag", "Tag")
                        .WithMany("GameTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamUserAchievement", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamAchievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.UserSteamProfile", "UserSteamProfile")
                        .WithMany()
                        .HasForeignKey("SteamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("UserSteamProfile");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamUserGame", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SteamGame", "Game")
                        .WithMany("UserGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.UserSteamProfile", "UserSteamProfile")
                        .WithMany("UserGames")
                        .HasForeignKey("SteamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("UserSteamProfile");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPost", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("SocialPosts")
                        .HasForeignKey("AuthorAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostAttachment", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.SocialPost", "Post")
                        .WithMany("Attachments")
                        .HasForeignKey("SocialPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostComment", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AuthorAppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SocialPostComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AchievementTracker.Data.Entities.SocialPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("SocialPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostReaction", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.SocialPost", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("SocialPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserRole", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AchievementTracker.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserSteamProfile", b =>
                {
                    b.HasOne("AchievementTracker.Data.Entities.UserExternalLogin", "ExternalLogin")
                        .WithOne("SteamProfile")
                        .HasForeignKey("AchievementTracker.Data.Entities.UserSteamProfile", "UserExternalLoginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExternalLogin");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.AppUser", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("SocialPosts");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamAchievement", b =>
                {
                    b.Navigation("Stats");

                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamCategory", b =>
                {
                    b.Navigation("GameCategories");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamDeveloper", b =>
                {
                    b.Navigation("GameDevelopers");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGame", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("GameCategories");

                    b.Navigation("GameDevelopers");

                    b.Navigation("GameGenres");

                    b.Navigation("GameLanguages");

                    b.Navigation("GamePublishers");

                    b.Navigation("GameTags");

                    b.Navigation("Platforms");

                    b.Navigation("Prices");

                    b.Navigation("Reviews");

                    b.Navigation("UserGames");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamGenre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamLanguage", b =>
                {
                    b.Navigation("GameLanguages");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamPublisher", b =>
                {
                    b.Navigation("GamePublishers");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SteamTag", b =>
                {
                    b.Navigation("GameTags");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPost", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.SocialPostComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserExternalLogin", b =>
                {
                    b.Navigation("SteamProfile");
                });

            modelBuilder.Entity("AchievementTracker.Data.Entities.UserSteamProfile", b =>
                {
                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
