export const PROFILE_LATEST_ACTIVITY_INITIAL_VISIBLE_COUNT = 5;
export const PROFILE_LATEST_ACTIVITY_SHOW_MORE_BATCH_SIZE = 5;

export const PROFILE_ACHIEVEMENT_GRID_INITIAL_VISIBLE_COUNT = 24;
export const PROFILE_ACHIEVEMENT_GRID_SHOW_MORE_BATCH_SIZE = 24;

export const ACHIEVEMENT_HOVER_CARD_OPEN_DELAY_MS = 180;

export const PROFILE_API_GAMES_PAGE_SIZE = 100;
export const PROFILE_API_ACHIEVEMENTS_PAGE_SIZE = 100;
export const PROFILE_API_ACHIEVEMENTS_BY_POINTS_PAGE_SIZE = 100;
export const PROFILE_API_LATEST_ACTIVITY_PAGE_SIZE = 100;
